# Generated by Django 4.1 on 2023-09-11 19:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='message',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat',
            name='response',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
